services:
  client:
    build:
      context: ./client
    ports:
      - "5000:80"
    networks:
      - app-network

  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge