services:
  client:
    build:
      context: ./client
    ports:
      - "80:80"
    networks:
      - app-network

  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    networks:
      - app-network
    env_file:
      - .env
      - .env.local

networks:
  app-network:
    driver: bridge